[build]
  # Sostituisci 'dist' con il nome della cartella di output del tuo build (solitamente 'dist' per Vite)
  publish = "dist" 
  command = "npm run build" # Assicurati che il comando di build sia corretto

[functions]
  directory = "netlify/functions"

[[redirects]]
  # REGOLA FONDAMENTALE PER LE SPA.
  # Dice a Netlify: "Se non trovi un file corrispondente, servi index.html"
  from = "/*"
  to = "/index.html"
  status = 200