[build]
  publish = "dist" # Deve corrispondere all'impostazione Netlify

[[redirects]]
  # Questa regola Ã¨ FONDAMENTALE.
  # Dice: per qualsiasi URL non trovato (/*), servi index.html e rispondi 200 (OK).
  from = "/*"
  to = "/index.html"
  status = 200